---
config:
  theme: forest
---
sequenceDiagram
    participant M as Master

    actor C1 as Client1
    %% actor C2 as Client2
    participant R1 as Replica1(coordinator)
    participant R2 as Replica2
    participant R3 as Replica3
    participant R4 as Replica4

    rect rgba(0, 255, 0, 0.3)
        note over R3: Notes that Replica1 has crashed

        note over R3: Transaction ELECTION init on R3 having <2,4>
        R3 ->> R4: ElectionMsg((3,<2,4>))
        note over R3: Timeout for ACK Msg starts

        note over R4: Transaction ELECTION init on R4 having <2,5>
        R4 ->> R3: ElectionAck()
        R4 ->> R2: ElectionMsg((3,<2,4>), (4,<2,5>))
        note over R4: Timeout for ACK Msg starts
    
        note over R2: Transaction ELECTION init on R2 having <2,3>
        R2 ->> R4: ElectionAck()
        R2 ->> R3: ElectionMsg((3,<2,4>), (4,<2,5>), (2,<2,3>))
        note over R2: Timeout for ACK Msg starts


        R3 ->> R2: UpdateAck(idx)
        R3 ->> R4: UpdateMsg((3,<2,4>), (4,<2,5>), (2,<2,3>))
        note over R3: Timeout for ACK Msg starts

        R4 ->> R3: ElectionAck()
        note over R4: R4 notices that is the new coordinator
        R4 ->> R2: SynchronizationMsg(epoch, 0)
        R4 ->> R3: SynchronizationMsg(epoch, 0)
        
    end
    


